# -*- mode: ruby -*-
# vi: set ft=ruby :
projectPath = File.dirname(File.dirname(File.dirname(File.dirname(__FILE__))))
mountDir = "/home/ubuntu/axe-grinder"

Vagrant.configure("2") do |config|

    # configure VM
    config.vm.box = "ubuntu/xenial64"

    # configure provisioning
    config.vm.provision "shell", path: "bootstrap.sh", privileged: true
    config.vm.provision "shell", path: "install_xpack.sh", privileged: true
    config.vm.provision "shell", path: "../provision/node/nvm.sh", privileged: false

    # configure network ports
    config.vm.network "forwarded_port", host: 9200, guest: 9200 # Elasticsearch
    config.vm.network "forwarded_port", host: 9300, guest: 9300 # Logtash
    config.vm.network "forwarded_port", host: 5601, guest: 5601 # Kibana

    config.vm.provider "virtualbox" do |vb, override|
        vb.cpus = 1
        vb.memory = 4096
        vb.gui = false
        vb.name = "elastic5x-ubuntu16"
        override.vm.synced_folder "./provision", "/ubuntu"
        override.vm.synced_folder projectPath, mountDir, group: "www-data", mount_options: ['dmode=0775','fmode=0775']


        # disable the vbguest update plugin
        if Vagrant.has_plugin?("vagrant-vbguest")
            override.vbguest.auto_update = false
        end
    end
end
